require: rubocop-rspec

# Remove these configuration records
# one by one as the offenses are removed from the code base.

Metrics/AbcSize:
  Max: 20 # Goal: 15

Metrics/CyclomaticComplexity:
  Max: 8 # Goal: 7

Metrics/PerceivedComplexity:
  Max: 9 # Goal: 7

Naming/MemoizedInstanceVariableName:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

# It may be possible for us to use safe_load, but we'd have to pass the
# safelists, like `whitelist_classes` into our serializer, and the serializer
# interface is a public API, so that would be a breaking change.
Security/YAMLLoad:
  Enabled: false

# We want this, but not until we drop support for ruby 2.4
Style/HashTransformKeys:
  Enabled: false

# We want this, but not until we drop support for ruby 2.4
Style/HashTransformValues:
  Enabled: false
