language: ruby
cache: bundler

# For ruby, we test the highest and lowest minor versions only.
rvm:
  - 2.4
  - 2.7

env:
  global:
    - TRAVIS=true
  matrix:
    - DB=mysql
    - DB=postgres
    - DB=sqlite

# We want to use `sudo: false` because the container infrastructure is supposed
# to be faster, but Travis is having issues with containers lately ..
#
# > No output has been received in the last 10m0s
#
# .. and they recommend we use the VM infrastructure (`sudo: required`) in
# the meantime.
sudo: required

before_install:
  - gem update bundler

gemfile:
  - gemfiles/ar_5.2.gemfile
  - gemfiles/ar_6.0.gemfile
matrix:
  exclude:
    # rails 6 requires ruby >= 2.5.0
    - rvm: 2.4
      gemfile: gemfiles/ar_6.0.gemfile
  fast_finish: true
services:
  - mysql
  - postgresql
